### PR TITLE
update version

### PR DESCRIPTION
**Pull request by stackoverfloweth**

### CODE REVIEW

**Comment by pleek91** [comment]
Was this released? I think a `npm version patch` would also update the package-lock.json

**Comment by stackoverfloweth** [comment]
> I think a `npm version patch` would also update the package-lock.json so might want to double check that.

@pleek91 great suggestion. I also decided to use this PR to do some other housekeeping in preparation for the first "real release"

- updated readme
- moved internal stuff into `utilities`, not exporting from index
- added `has` and `clear` methods to mapper
- updated `register` to accept a single profile in addition to array of profiles
- wrote a test for that ^

**Review by pleek91 — APPROVED** [review]
Nice! Next up vitepress docs?

**Comment by stackoverfloweth** [comment]
> Nice! Next up vitepress docs? 

I was thinking about it lol.

**Pull request merged**
